# frozen_string_literal: true

source 'https://rubygems.org'

#ruby '~> 3.0.2'


# Choose between PostgreSQL and MySQL (comment out one of the following gems)
gem 'pg'
gem 'sqlite3'
gem 'mysql2'
gem 'listen'
gem 'better_errors'
gem 'webrick'
gem 'sweetalert2'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.1.4'
# Use Puma as the app server
# Use SCSS for stylesheets
gem 'sass-rails'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'
# Turbolinks makes navigating your web application faster. Read more:
# https://github.com/turbolinks/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1', '>= 3.1.11'

gem 'bootstrap-sass'
# List of countries and their respective states and cities
gem 'city-state'
# Authentication
gem 'devise'
# Generate fake user names, e-mails, adresses, IPs, lorem text, etc. Include
# in all environments as we might use it to seed the DB in test deploys.
gem 'faker'
# Use slugs instead of IDs in URLs. Makes prettier URLs, improves SEO and avoids
# leaking DB IDs (for security reasons).
gem 'friendly_id'
# jQuery is no longer installed by default on Rails 5.1
gem 'jquery-rails'
# Pagination
gem 'kaminari'
# Authorization
gem 'pundit'
# Contact form
gem 'mail_form'
# HTTP caching
gem 'rack-cache'
# Locale data for Rails. Rails already comes with i18n capabilities (e.g.,
# translate model attributes, possibility to place all of the app's strings in
# YML dictionaries). Only use this gem if you need to translate Rails to one or
# more non-english languages.
# gem 'rails-i18n', '~> 5.0.0'
# Searching, filtering and sorting
gem 'ransack'
# Advanced select boxes https://select2.github.io/
gem 'select2-rails'
# Get e-mail notifications when exceptions happen in the production environment
gem 'exception_notification'

gem 'administrate'
#gem 'sidekiq'#
gem 'searchkick'
#gem 'chartkick'
#gem 'hightop'
#gem 'by_star'
#gem 'groupdate'
gem 'blazer'
#gem 'wisper'
#gem 'redis_objects'
gem 'administrate'

